### ISSUE TITLE
tb-form layouts should not be defined via attributes

### ISSUE THREAD

**Issue by mariodivece** [unosquare/tubular#1]
Looking here: http://unosquare.github.io/tubular/#/FormGenerator
I select 2-columns and 3-columns layouts. Layousts should be semantically defined and generated. This should not be an option at the form level and the generator needs to define the layouts as elements. In other words, avoid the use of attribute layout="three-columns"

Scenario: You have a form with an accordion of fields. You get the pictore of what happens if you nest an accordion within the fb-form directive.

**Comment by geoperez** [comment]
The layout attribute was removed, but @mariodivece what is your suggestion to handle layouts?

**Comment by mariodivece** [comment]
make it semantic... ie, <div> elements with row and col-md attributes. The usual! Let me know if you still don't get it.

**Comment by geoperez** [comment]
Semantic col-md's are generated now.
