### ISSUE TITLE
AuthInterceptor doesn't work in IE

### ISSUE THREAD

**Issue by Alexey-Unosquare** [unosquare/tubular#113]
this method is not supported https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by geoperez** [comment]
I recommend include the polyfill in your project, we don't want to continue supporting IE.

**Comment by Alexey-Unosquare** [comment]
Would be great if that were explicitly mentioned in the tubular documentation.

**Comment by geoperez** [comment]
Sure, I'm going to specify the browser compatibility.

**Comment by Alexey-Unosquare** [comment]
Closing as it's not relevant anymore
