### ISSUE TITLE
tb-form-buttons directive needs to be removed

### ISSUE THREAD

**Issue by mariodivece** [unosquare/tubular#3]
This directive needs to be removed altogether. Buttons and containing panels are simple elements that the generator should be able to handle without a special directive.

![image](https://cloud.githubusercontent.com/assets/351978/7466475/40c0c444-f2a9-11e4-8543-f1d6d487e2ef.png)

**Comment by geoperez** [comment]
I removed the tbFormButtons directive, and a simple div with the buttons was added to the Template Service.
