### ISSUE TITLE
tb-checkbox needs to be replaced by something that holds values

### ISSUE THREAD

**Issue by mariodivece** [unosquare/tubular#4]
Traditionally, the checkbox field in HTML has caused issues because unchecking it CLEARS the value while checking it HOLDS the value. Replace this directive in order to:
1. Have it define 3 attributes: checked-value, unchecked-value and value
2. Have it use better graphics
3. Have validation actually work! See screenshots below of what happens when I uncheck the checkbox:

Here's the "Required" checkbox checked.

![image](https://cloud.githubusercontent.com/assets/351978/7466522/4886993c-f2aa-11e4-83d3-2b278a165539.png)

Now, UN-checking the checkbox results in the following error message:

![image](https://cloud.githubusercontent.com/assets/351978/7466525/7ecfe2f0-f2aa-11e4-93d4-d68c8ca00ae2.png)

**Comment by geoperez** [comment]
Would you prefer to use a Boostrap button to show checkboxes? Something like this: https://angular-ui.github.io/bootstrap/#/buttons

**Comment by mariodivece** [comment]
No, those are HORRIBLE. Use unchecked and checked icons from font-awesome to make a decent-looking checkbox.

**Comment by geoperez** [comment]
I updated Tubular and the Generator with a new checkbox control, using FontAwesome. Could you take a look pls?

**Comment by mariodivece** [comment]
It looks good. Maybe try to make it a little larger (proportional to the text fields) and also ensure that the checkbox is touch-enabled.

**Comment by geoperez** [comment]
Aright, I'll test it in android.

On Thu, May 7, 2015 at 12:11 PM, Mario Di Vece notifications@github.com
wrote:

> It looks good. Maybe try to make it a little larger (proportional to the
> text fields) and also ensure that the checkbox is touch-enabled.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/unosquare/tubular/issues/4#issuecomment-99941153.

## 

Geo Pérez

**Comment by geoperez** [comment]
The icon was using the same size as the label, but I set it now to 120%.

Also I tested it with Android and iOS, and it is working fine.
