### ISSUE TITLE
The checkbox style is applied in all DOM

### ISSUE THREAD

**Issue by Vic30** [unosquare/tubular#6]
When the tubular style is imported, this change the checkbox in all the DOM.
it´s cool, But should be applied only in the checkboxes inner to tubular grids and not affect the checkboxes in the DOM.

![image](https://cloud.githubusercontent.com/assets/10277735/8237928/36d6c5a0-15b8-11e5-905b-d85506b08fbc.png)

**Comment by geoperez** [comment]
Ok, I'll add a class to identify tubular controls only.

**Comment by mariodivece** [comment]
Please follow the same design principle as bootstrap. IIf you want to apply the nice tubular checkbox class, you need to set it accordingly in the class attribute with the tubular-checkbox class (or whatever the prefix and suffix standard notation is currently applicable).

**Comment by geoperez** [comment]
The class is tubular-checkbox now, also tubular-radio.
