### ISSUE TITLE
Paginator not working properly when clicking the "last page" button (http://unosquare.github.io/tubular/#/Basic)

### ISSUE THREAD

**Issue by kadosh** [unosquare/tubular#8]
After clicking the "last page" button the data table starts doing several requests to the server. It seems that the data table is trying to get the last page but going one by one.

![image](https://cloud.githubusercontent.com/assets/399019/10314164/01a15f46-6c19-11e5-9d92-9a267a68856f.png)

**Comment by geoperez** [comment]
Hello Mr. PHP, I gonna take a look.

**Comment by geoperez** [comment]
@kadosh can you check again please?
