### ISSUE TITLE
NuGet Package incompatible with .NET 4.5

### ISSUE THREAD

**Issue by mariodivece** [unosquare/tubular#91]
Please update the NuGet package Tubular.ServerSide to also include a build for .NET 4.5

**Comment by geoperez** [comment]
I merged the tubular and tubular-core project. Targeting Net Fx 4.5.2 and NET Core.

**Comment by mariodivece** [comment]
The NuGet is 1.0.8 correct?

**Comment by geoperez** [comment]
Yes

**Comment by mariodivece** [comment]
Ok, tested with embedio samples. Closing.
