### ISSUE TITLE
Overlays looks misaligned and horrible.

### ISSUE THREAD

**Issue by mariodivece** [unosquare/tubular#92]
All overlays seem to have alignment issues. The grid looks awful. Maybe use something like Tether to help out?
http://tether.io/

**Comment by geoperez** [comment]
Alignment issues with the overlay? can you elaborate?

**Comment by mariodivece** [comment]
When the grid refreshes or when a form is submitted, the overlays are larger than the grid or form area. Looks really bad. See TimeCore's Login screen for example.

**Comment by mariodivece** [comment]
Is this fixed yet? It's been so long . . .

**Comment by kadosh** [comment]
This has been fixed by @greciaveronica. Closing it.
